# Generated by Django 5.0.6 on 2024-11-08 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create_articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savearticles',
            name='created_at',
        ),
    ]
