# Generated by Django 5.0.6 on 2024-11-08 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_articles', '0002_remove_savearticles_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='savearticles',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='savearticles',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
